FROM node:22 as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
# Eliminar la configuración predeterminada
RUN rm /etc/nginx/conf.d/default.conf
# Copiar nuestra configuración personalizada
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Copiar los archivos compilados
COPY --from=build /app/dist/frontend/browser /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]